# Generated by Django 5.2.17 on 2026-10-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Ж', 'Женский'), ('М', 'Мужской')], default='Ж', max_length=1, verbose_name='Пол'),
        ),
    ]
