services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8005:80"
  #   restart: always
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./static/:/var/www/daystat/static/

  caddy:
    image: caddy:2
    ports:
      - "8005:80"
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  app:
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./static/:/var/www/daystat/static/
