services:
  caddy:
    image: caddy:2
    ports:
      - "127.0.0.1:8005:80"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./static/:/srv/daystat/static/

  app:
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./static/:/app/static/
      - ./db.sqlite3:/app/db.sqlite3
