server {
    listen 80;

    location / {
        proxy_pass http://app:8000;
    }

    location /static/ {
        alias /var/www/daystat/static/;
    }

    location /favicon.ico {
        alias /var/www/daystat/static/img/favicon.ico;
    }
}
