# Generated by Django 5.1 on 2024-08-19 12:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Сумма')),
                ('note', models.CharField(blank=True, max_length=128, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-created_at', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Daystat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('week', models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MaxValueValidator(53)], verbose_name='Неделя')),
                ('calories', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5000)], verbose_name='Количество калорий, ккал')),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Вес, кг')),
                ('period_start', models.BooleanField(default=False, verbose_name='Начало цикла')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daystats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика за день',
                'verbose_name_plural': 'Статистики за день',
                'ordering': ['-date', 'user'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='One user can only have one record per day')],
            },
        ),
    ]
