# Generated by Django 5.1 on 2024-08-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daystats', '0002_remove_daystat_updated_at_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at', 'user'], 'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
    ]
