# Generated by Django 5.2.17 on 2026-10-03 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystats', '0003_expense_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystat',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='Количество калорий, ккал'),
        ),
        migrations.AlterField(
            model_name='daystat',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)], verbose_name='Вес, кг'),
        ),
    ]
