# Generated by Django 5.1 on 2024-08-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystats', '0003_alter_expense_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Примечание'),
        ),
    ]
