# Generated by Django 5.1 on 2024-08-19 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystats', '0004_expense_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='week',
            field=models.PositiveSmallIntegerField(default=1, editable=False, validators=[django.core.validators.MaxValueValidator(53)], verbose_name='Неделя'),
            preserve_default=False,
        ),
    ]
