# Generated by Django 5.1 on 2024-08-19 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystats', '0005_expense_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='week',
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
    ]
